language: ruby
install:
- bundle install
script:
- bundle exec jekyll build
branches:
  only:
  - release
deploy:
- provider: s3
  access_key_id: "${S3_ACCESS_KEY_ID}"
  secret_access_key: "${S3_SECRET_KEY}"
  bucket: developer.sagebridge.org
  skip_cleanup: true
  acl: public_read
  detect_encoding: false
  endpoint: https://developer.sagebridge.org.s3-website-us-east-1.amazonaws.com
  local_dir: _site
  on:
    branch: release
