title: Bridge Developer Portal
email: bridgeit@sagebase.org
description: Developer portal the Bridge mobile health research platform
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "tables", "with_toc_data"]
collections:
  articles:
    output: true